# Deployment.yaml.template
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a1d1c518-5ad9-48dc-80b6-be2881b00aba-nodejs-app
  namespace: local
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs
        image: /nodejs-image:latest
        ports:
        - containerPort: 3000
