stages:
- deploy

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: your-aws-region

deploy:
  stage: deploy
  image: python:latest # Puedes usar cualquier imagen que tenga el cliente de AWS (awscli) instalado
  script:
  - cd iac/lambda/visitor
  - zip -r visitor_lambda.zip .
  - aws lambda update-function-code --function-name YourLambdaFunctionName --zip-file fileb://visitor_lambda.zip
  - cd ../root
  - zip -r root_lambda.zip .
  - aws lambda update-function-code --function-name YourLambdaFunctionName --zip-file fileb://root_lambda.zip
  only:
  - main
